title: Blaxon
description: 记录与备份 —— 属于自己的数字资产
lang: zh-CN
timezone: Asia/Shanghai

theme: minima
minima:
  skin: classic

url: "https://blaxon.github.io"
baseurl: ""

permalink: /posts/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

show_excerpts: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
