baseURL = 'https://xanderhang.com/'
locale = 'zh-cn'
hasCJKLanguage = true
title = 'XanderHang'
theme = 'hugo-paper'

[outputs]
  home = ["HTML", "RSS"]

[pagination]
  pagerSize = 5

[services]
  [services.googleAnalytics]
    ID = "G-0QZZR18RF7"

[params]
  description = "记录与备份 —— 属于自己的数字资产"
  color = "light"
  mainSections = ["blog"]

  name = "XanderHang"
  bio = "QA Engineer · Gamer · Open Source Enthusiast"
  avatar = "https://xanderhang.com/favicon.png"

  [params.giscus]
    repo = "Blaxon/blaxon.github.io"
    repoId = "R_kgDOT3OrlQ"
    category = "Comments"
    categoryId = "DIC_kwDOT3Orlc4DEIwq"
    mapping = "url"
    lang = "zh-CN"

  [[params.social]]
    label = "Discord"
    url = "https://discord.gg/9BcyWcHpV"
    icon = "fa-brands fa-discord"

  [[params.social]]
    label = "GitHub"
    url = "https://github.com/Blaxon"
    icon = "fa-brands fa-github"

  [[params.social]]
    label = "Email"
    url = "mailto:contact@xanderhang.com"
    icon = "fa-regular fa-envelope"

[menu]
  [[menu.main]]
    name = "博客"
    pageRef = "blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "关于"
    pageRef = "about"
    url = "/about/"
    weight = 3

  [[menu.main]]
    name = "装备"
    pageRef = "uses"
    url = "/uses/"
    weight = 4

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "monokai"

[taxonomies]
  tag = "tags"
